/**********************************************************************

	--- Qt Architect generated file ---

	File: AddressBookAboutData.h
	Last generated: Fri Jul 24 15:58:23 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AddressBookAboutData_included
#define AddressBookAboutData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbt.h>

class AddressBookAboutData : public QDialog
{
    Q_OBJECT

public:

    AddressBookAboutData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AddressBookAboutData();

public slots:


protected slots:


protected:
    QLabel* labelFrame;
    QLabel* labelLogo;
    QLabel* labelVersion;
    QLabel* labelAuthor;
    QPushButton* buttonOK;

};

#endif // AddressBookAboutData_included
